server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always
